Migrated etcd to new, faster version

diff --git a/test b/test
--- a/test
+++ b/test
@@ -13,6 +13,7 @@ set -e
 # Invoke ./cover for HTML output
 COVER=${COVER:-"-cover"}
 
+GO_BUILD_FLAGS=-a
 source ./build
 
 # Hack: gofmt ./ will recursively check the .git directory. So use *.go for gofmt.
@@ -87,6 +88,18 @@ function fmt_tests {
 			exit 255
 		fi
 	done
+
+	echo "Checking goword..."
+	# get all go files to process
+	gofiles=`find $FMT -iname '*.go' 2>/dev/null`
+	# ignore tests and protobuf files
+	gofiles=`echo ${gofiles} | sort | uniq | sed "s/ /\n/g" | egrep -v "(\\_test.go|\\.pb\\.go)"`
+	# only check for broken exported godocs
+	gowordRes=`goword -use-spell=false ${gofiles} | grep godoc-export | sort`
+	if [ ! -z "$gowordRes" ]; then
+		echo -e "goword checking failed:\n${gowordRes}"
+		exit 255
+	fi
 
 	echo "Checking for license header..."
 	licRes=$(for file in $(find . -type f -iname '*.go' ! -path './Godeps/*'); do
